project_name: contentfulvalidation

release:
  github:
    owner: foomo
    name: contentfulvalidation
  prerelease: auto

builds:
  - skip: true

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

changelog:
  use: github-native
